hspec/hspec

CHANGES.markdown
hspec-core/hspec-core.cabal
hspec-core/src/Test/Hspec/Core/Formatters.hs
hspec-core/test/Test/Hspec/Core/FormattersSpec.hs
hspec-discover/hspec-discover.cabal
hspec.cabal

Lots of tools (e.g. vim's quickfix) know how to parse gcc messages (and
allow you to jump to source locations).
See below for how the messages in this branch look like. I'm not overly passionate about the exact message format, but this seems to be the most logical to me and it works with vim's quickfix and geany.
```
Dev
something
foo FAILED [1]
bar
baz FAILED [2]
boo FAILED [3]
Failures:
dev/DevSpec.hs:15: (best-effort)
1) Dev.something foo
expected: False
but got: True
dev/DevSpec.hs:18: (best-effort)
2) Dev.something.bar baz
dev/DevSpec.hs:20: (best-effort)
3) Dev.something.bar boo
Source locations marked with "best-effort" are calculated heuristically and may be incorrect.
Randomized with seed 1677688156
```

format source location messages to look like gcc messages

---

CHANGES.markdown
README.markdown
hspec-discover/src/Run.hs
hspec-discover/test/RunSpec.hs

Tweaks `fileToSpec` so that it rejects files with invalid module names,
as discussed in #221. Please let me know if you'd like me to test or
change anything. I know I shouldn't have refactored the function as well
as adding this feature, but I thought it looked a little clearer like
this.
Let me know what you think.

hspec-discover: Reject invalid module names

---

.travis.yml
CHANGES.markdown
hspec-core/hspec-core.cabal
hspec-core/src/Test/Hspec/Core/Example.hs
hspec-discover/hspec-discover.cabal
hspec.cabal

This fixes a warning about non-exhaustive pattern-matches.
@sol: Please review, if you can.

Compatibility with QuickCheck 2.8

---

README.markdown
doc/parallel-spec-execution.md
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/src/Test/Hspec/Core/Runner/Eval.hs
hspec-core/src/Test/Hspec/Options.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs

For some jobs, particularly when running in an environment like travis-ci, running a huge number of parallel tests can cause memory exhaustion and/or poor performance.  This patch allows hspec to be invoked with a -j or --jobs option to limit this parallelism.  The current default behavior, allowing unlimited jobs in parallel, remains the default.  An --unlimited-jobs switch to explicitly invoke the default behavior is also included for completeness.

Add -j/--jobs and --unlimited-jobs to allow users to limit parallelism

---

CHANGES.markdown
hspec-core/src/Test/Hspec/FailureReport.hs

This is a workaround for https://github.com/ghcjs/ghcjs/issues/263
The test-suite of `hspec` currently doesn't run with `ghcjs` because the functions from `silently` also don't work with `ghcjs`. However I have been able to successfully run other `hspec` test-suites compiled with `ghcjs` with this branch.
Once `silently` works with `ghcjs` the tests for `FailureReport` have to be omitted with that compiler. I didn't want to include any `CPP` code for that yet, because the test-suite doesn't run anyways.
@sol: Are you still fine with merging this, pending travis?
(cc: @luite)

workaround for ghcjs

---

doc/index.markdown

Inspired by `hspec-attoparsec`, these utilities should reduce boilerplate for those who need to test [Megaparsec](https://hackage.haskell.org/package/megaparsec) parsers with Hspec.

Add ‘hspec-megaparsec’ to list of extensions

---

hspec-core/src/Test/Hspec/Core/Util.hs

This was the bug I originally thought was caused by #269 (I am pretty sure there is still a separate issue when running in parallel).
The problem is that when the main thread exits all other threads are killed instantly without even being noticed about it. `withAsync` helps somewhat as it throws an exception to these threads. However it returns after the exception has been raised which does not mean that the finalizers have finished running. You thus run into cases where your finalizer is abruptly terminated somewhere in the middle. By waiting we make sure that all the finalizers have been run.
Obviously this means that we can deadlock if a finalizer never returns, but that is always the case for `bracket` and imho leaking resources (in my case I was leaking temporary databases) is a lot …

Block until finalizers return

---

README.markdown

Its nice to have a travis build badge on the readme, but if I follow that link, the build is actually mostly broken. Not sure why.
Update: This PR built without a problem. Not sure what was happening before.

README.markdown: Add a travis build badge

---

hspec-core/src/Test/Hspec/Core/Hooks.hs

In trying to track down an unrelated problem, I inlined these two functions as they're quite cryptically point-free and seem to be clearer like this.

Inline untangle and mapAround

---

hspec-core/src/Test/Hspec/Core/Compat.hs

GHC 8.2 reshuffled around the internals of `Typeable` quite a bit, and as a result, `base` no longer exports the `Data.Typeable.Internal` module in that version. This causes `hspec-core` (and `hspec-meta`) to fail to build on GHC 8.2.
But this is quite easily fixable, as `hspec` is only using `Data.Typeable.Internal` to import `tyConModule` and `tyConName`, which have been exported from the public `Data.Typeable` interface since GHC 7.4. Thus, we only need import from `Data.Typeable.Internal` on very old GHCs.
While this fixes the `hspec-core` issue, I don't know how to make the same change to `hspec-meta`, as I don't know where it lives.

Don't import from Data.Typeable.Internal when possible (i.e., add support for GHC 8.2)

---

doc/css/custom.less

Hello. macOS does not come with `Liberation Mono` installed thus the current documentation monospace font stack falls back to `Courier New`. As you can see in the screenshot below it looks _extremely_ thin. I thought I'd try to add a couple better options using only fonts installed by default on this platform.
Courier New
---
This is the present:
Menlo
---
It's the default for the Apple's shell program `Terminal.app` it has been in OS X forever. Incidentally https://play.golang.org uses it too.
Courier
---
If `Menlo` is not available at the very least try `Courier` before `Courier New`. It looks like this:
Thanks for taking the time to look through this.

doc: Improve monospace font stack on macOS

---

CHANGES.markdown
hspec-discover/hspec-discover.cabal
hspec-discover/package.yaml
hspec-discover/src/Test/Hspec/Discover/Run.hs
hspec-discover/src/Test/Hspec/Discover/Sort.hs
hspec-discover/test/Test/Hspec/Discover/RunSpec.hs
hspec-discover/test/Test/Hspec/Discover/SortSpec.hs

I would like my tests to be [sorted for humans](https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/). It seems easy to add to `hspec-discover`, would you consider something like this?

Change hspec-discover sort from lexicographic to to natural order

---

hspec-core/src/Test/Hspec/Core/QuickCheckUtil.hs

* Remove formatLabels because QC no longer defines formatLabel. (This function wasn't called anyway, it seems.)
* Remove InsufficientCoverage, which no longer exists.

QuickCheck 2.12 compatibility.

---

CHANGES.markdown
hspec-core/src/Test/Hspec/Core/Clock.hs
hspec-core/src/Test/Hspec/Core/Formatters.hs
hspec-core/test/Helper.hs
hspec-core/test/Test/Hspec/Core/FormattersSpec.hs

@nh2 what do you think about thin change?  Do you think 2 seconds is appropriate?  Is it crucial to print a warning, e.g. "diff calculation took longer than 2 seconds and was interrupted; not showing diff".
This seems to work well within ghci, but not sure about compiled test suites.  I see a chance that `timeout` won't work reliably if you hog a CPU, but I haven't tried.

Interrupt diff calculation after two seconds (see #415)

---

doc/parallel-spec-execution.md

docs: Clarify that `-j` is an Hspec option (as opposed to an RTS option)

---

.gitignore
hspec-core/src/Test/Hspec/Core/Hooks.hs
hspec-core/test/Test/Hspec/Core/HooksSpec.hs

I can see there have been several attempts to add a `beforeAllWith` hook in the past, but I'd like to revisit the question.
My use case is as follows:
I'm writing a suite for one part of a larger application. All of the existing tests are passed a test environment via `beforeAll`, and my suite needs to be combined with the other suites to form the top-level suite. However, the part of the application I'm testing has some different characteristics from the rest of the application and I don't want to pollute the main test environment with things that are specific to just one suite. I'd therefore like to wrap my suite with a `beforeAllWith` that in turn wraps the main test environment with a more specific one that includes some extra resources.
I want the entire test app to look like this: …

Add beforeAllWith

---

doc/quickcheck.md

If a test fails, this will show "expected ... but got ..." instead of just the value generated by QuickCheck, which is 1000x more useful.

Use `shouldBe` instead of == in property test docs.

---

doc/_includes/QuickCheck.hs
doc/quickcheck.md

* `shouldBe` is now available in property blocks thanks to quickcheck-io.
* Introduce the utility function `prop`.

Update quickcheck.md to follow the latest hspec

---

hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs
hspec-core/src/Test/Hspec/Core/Formatters/Monad.hs

Output is now instead suppressed by writeTransient when running with
--no-color.

Call exampleProgress even when running with --no-color

---

CHANGES.markdown
hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs
hspec-core/src/Test/Hspec/Core/Formatters/Monad.hs
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/test/Test/Hspec/Core/FormattersSpec.hs

getFinalCount returns the final number of examples that will have been
encountered in this run. (The name is slightly non-obvious, but
getTotalCount was already taken.) This allows formatters to report
total run progress as a ratio or a percentage, or display a filling
progress bar, etc.

Add getFinalCount to Formatter API

---

CHANGES.markdown
hspec-discover/src/Test/Hspec/Discover/Run.hs
hspec-discover/test/Test/Hspec/Discover/RunSpec.hs
src/Test/Hspec/Discover.hs

Use -XNoImplicitPrelude for hspec-discover generated test drivers

---

CHANGES.markdown
hspec-discover/src/Test/Hspec/Discover/Run.hs

hspec-discover: Deprecate `--no-main` and `--formatter`

---

CHANGES.markdown
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs

(we first need to sort out any Unicode output issues, see #512)

REVERT: Use "checks" formatter by default (close #489)

---

hspec-core/src/Test/Hspec/Core/Config/Definition.hs
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/src/Test/Hspec/Core/Runner/Eval.hs
hspec-core/test/Test/Hspec/Core/HooksSpec.hs

(so that it matches the command-line flag `--fail-fast`)

Rename configFastFail to configFailFast

---

CHANGES.markdown
hspec-discover/integration-test/hspec-discover-integration-tests.cabal
hspec-discover/integration-test/with-config/FooSpec.hs
hspec-discover/integration-test/with-config/Spec.hs
hspec-discover/integration-test/with-config/SpecConfig.hs
hspec-discover/src/Test/Hspec/Discover/Run.hs
hspec-discover/test/Test/Hspec/Discover/RunSpec.hs
src/Test/Hspec/Discover.hs

After discussing this with @soenkehahn, I'm inclined to reconsider going with #555 instead.
This reverts commit ec713883740b5134f32b27b7863fe5753f3acbd3 (https://github.com/hspec/hspec/pull/527).

Revert "hspec-discover: Add support for custom configs"

---

CHANGES.markdown
hspec-core/src/Test/Hspec/Core/Formatters/V2.hs
hspec-core/test/Test/Hspec/Core/Formatters/V2Spec.hs
hspec-core/vendor/Text/Show/Unicode.hs

This turns e.g.
expected: "\956"
but got: "\955"
into
expected: "μ"
but got: "λ"

Recover unicode from ExpectedButGot (close #384)

---

hspec-core/src/Test/Hspec/Core/Util.hs
hspec-core/vendor/Text/Show/Unicode.hs

(for compatibility with `base-4.5.*`)

Text.Show.Unicode: Don't use (Applicative ReadP) (close #576)

---

hspec-core/hspec-core.cabal
hspec-core/package.yaml
hspec-core/vendor/Control/Concurrent/Async.hs
hspec-core/vendor/stm-2.5.0.1/Control/Concurrent/STM/TMVar.hs

This spares us from the following dependencies with older versions of GHC (<= 8.8.*):
- base-orphans
- functor-classes-compat
- generic-deriving
- hashable
- mtl
- nats
- stm
- text
- th-abstraction
- transformers-compat

Vendor Control.Concurrent.STM.TMVar from stm-2.5.0.1 for GHC <= 8.2.*

---

hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/test/Spec.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs
test/regression/issue-270/run.sh

Use `HSPEC_COLOR=no` or `--no-color` to opt out of this.

Assume --color by default when running on GitHub Actions

---

hspec-core/src/Test/Hspec/Core/Format.hs
hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/test/Test/Hspec/Core/Formatters/V2Spec.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs

GitHub Actions does not interpret `\r`.  For that reason any transient out is never erased, resulting in duplicated output.
Disabling progress reporting prevents that duplicated output.
Before:
After:

Disable progress reporting when `GITHUB_ACTIONS=true`

---

hspec-core/src/Test/Hspec/Core/Formatters/V2.hs
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/src/Test/Hspec/Core/Runner/Eval.hs
hspec-core/test/Test/Hspec/Core/Formatters/V2Spec.hs
hspec-core/test/Test/Hspec/Core/HooksSpec.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs

(instead of `Test.Hspec.Core.Formatters.V2`)

Handle pretty-printing in `Test.Hspec.Core.Runner.Eval`

---

hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs
hspec-core/test/Test/Hspec/Core/Formatters/InternalSpec.hs

This facilitates using `print` when debugging test cases.
Given:
```haskell
spec :: Spec
spec = do
describe "reverse" $ do
it "reverses a list" $ do
threadDelay 500000
putStrLn "Hi there 👋"
threadDelay 500000
reverse [1 :: Int, 2, 3] `shouldBe` [3, 2, 1]
```
Before:
After:

Ensure that interim output does not interfere with output from tests

---

hspec-core/src/Test/Hspec/Core/Hooks.hs
hspec-core/test/Test/Hspec/Core/HooksSpec.hs

This PR fixes an issue when the `release` action in `aroundAll_` and `aroundAllWith` is called when the `acquire` action was not, causing a deadlock.
This situation can happen with multiple `aroundAll_` / `aroundAllWith` when one of the earlier `acquire` action has failed but the `release` actions of uncalled `acquire` still get executed.
Fixes #679.

Call release only when acquired in hooks

---

hspec-discover/src/Test/Hspec/Discover/Config.hs
hspec-discover/src/Test/Hspec/Discover/Run.hs
hspec-discover/src/Test/Hspec/Discover/Sort.hs

The Hspec CI tests from GHC 7.4.1/base-4.5.0.0 (released 2 February 2012), so the following HLint suggestions have been ignored:
~~~
hspec-discover\src\Test\Hspec\Discover\Sort.hs:16:21-80: Warning: Use sortOn
Found:
sortBy (comparing ((\ (k, t) -> (naturalSortKey k, t)) . f))
Perhaps:
sortOn ((\ (k, t) -> (naturalSortKey k, t)) . f)
hspec-discover\src\Test\Hspec\Discover\Sort.hs:16:41-73: Suggestion: Use first
Found:
\ (k, t) -> (naturalSortKey k, t)
Perhaps:
Data.Bifunctor.first naturalSortKey
Note: increases laziness
~~~
`Data.List.sortOn` and `Data.Bifunctor.first` first provided by `base-4.8.0.0` (GHC 7.10.1, released April 2015).

HLint suggestions for `hspec-discover`

---

CHANGES.markdown
hspec-core/hspec-core.cabal
hspec-core/package.yaml
hspec-core/src/Test/Hspec/Core/Clock.hs

This is trading correctness for fewer dependencies.  One immediate
benefit of this change is that we will get GHC 9.2.1 support right now.
The new code uses getCurrentTime, which is not monotonic.  As a
consequence the new behavior is less accurate when:
- A test run spans a leap second
- The system clock is adjusted during a test run
Both of these events are reasonably rare, so I hope this is the right
thing to do.

Do not depend on clock

---

CHANGES.markdown
hspec-core/src/Test/Hspec/Core/Formatters.hs
src/Test/Hspec/Formatters.hs

Instead the module documentation now says that they are deprecated in favor of `Test.Hspec.Core.Formatters.V1`.
There is just too much code that will fail with `-Werror` otherwise.

Revert deprecation of Test.Hspec.Formatters and Test.Hspec.Core.Formatters

---

changes/716.md
hspec-core/help.txt
hspec-core/src/Test/Hspec/Core/Compat.hs
hspec-core/src/Test/Hspec/Core/Config/Definition.hs
hspec-core/src/Test/Hspec/Core/Format.hs
hspec-core/src/Test/Hspec/Core/Formatters/Diff.hs
hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs
hspec-core/src/Test/Hspec/Core/Formatters/V1.hs
hspec-core/src/Test/Hspec/Core/Formatters/V2.hs
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/test/Helper.hs
hspec-core/test/Test/Hspec/Core/Config/OptionsSpec.hs
hspec-core/test/Test/Hspec/Core/Formatters/DiffSpec.hs
hspec-core/test/Test/Hspec/Core/Formatters/InternalSpec.hs
hspec-core/test/Test/Hspec/Core/Formatters/V2Spec.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs

Suppress excessive diff output

---

changes/514.md
hspec-core/help.txt
hspec-core/hspec-core.cabal
hspec-core/package.yaml
hspec-core/src/Test/Hspec/Core/Config/Definition.hs
hspec-core/src/Test/Hspec/Core/Format.hs
hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs
hspec-core/src/Test/Hspec/Core/Formatters/V2.hs
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/test/SpecHook.hs
hspec-core/test/Test/Hspec/Core/Config/OptionsSpec.hs
hspec-core/test/Test/Hspec/Core/Formatters/InternalSpec.hs
hspec-core/test/Test/Hspec/Core/Formatters/V2Spec.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs

Allow the use of an external diff program, add `--diff-command`

---

CHANGES.markdown
src/Test/Hspec/QuickCheck.hs

I felt like these are missing. 
Feel free to close this PR if you don't think this helpers are needed.

Add `xprop` and `fprop`, which use `xit` and `fit`

---

changes/771.md
hspec-core/src/Test/Hspec/Core/Example.hs
hspec-core/src/Test/Hspec/Core/Runner/Eval.hs
hspec-core/src/Test/Hspec/Core/Runner/JobQueue.hs
hspec-core/test/Test/Hspec/Core/Runner/JobQueueSpec.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs

The runner operates under the assumption that all exceptions from spec
items are handled and converted to `Result`s.  This is ensured by
`safeEvaluateExample`.
If a user violates this assumption by manually modifying a spec item
with `mapSpecItem_` and omitting proper exception handling then this can
lead to a deadlock.
This change addresses this by no longer relying on that assumption.

Prevent deadlocks on unguarded exceptions in runner

---

CHANGES.markdown
changes/771.md
changes/779.md
changes/export-modifyConfig.md
hspec-core/hspec-core.cabal
hspec-core/src/Test/Hspec/Core/Formatters/Pretty.hs
hspec-core/test/Test/Hspec/Core/Formatters/PrettySpec.hs
hspec-discover/hspec-discover.cabal
hspec.cabal
version.yaml

- Fix a bug where `[]` would be pretty-printed as `""`
- Don't pretty-print if the expected and actual value would be equal after pretty-printing

Pretty-print improvements / fixes

---

.github/workflows/api-check.yml
.github/workflows/build.yml
hspec-core/src/Test/Hspec/Core/Compat.hs
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs

refactoring: Internally use types that more closely represent the domain

---

hspec-core/src/Test/Hspec/Core/Config.hs

From the [`getHomeDirectory` Haddocks](https://hackage.haskell.org/package/directory-1.3.8.1/docs/System-Directory.html#v:getHomeDirectory):
> The operation may fail with:
>
> - `UnsupportedOperation` The operating system has no notion of home directory.
> - [`isDoesNotExistError`](https://hackage.haskell.org/package/base-4.16.3.0/docs/System-IO-Error.html#v:isDoesNotExistError) The home directory for the current user does not exist, or cannot be found.
The motivating example for this PR is the WASM backend in GHC 9.6, as [WASI](https://wasi.dev/) does not support home directories.

Don't crash when home directories are unsupported

---

hspec-meta/vendor

Right now the following `stack.yaml`:
```
extra-deps:
- git: https://github.com/hspec/hspec
commit: c38a03dd8c23b3d73ad2685e89ff3b0a73a844a6
```
Yields:
```
Cloning c38a03dd8c23b3d73ad2685e89ff3b0a73a844a6 from https://github.com/hspec/hspec
Error: [S-760]
Unsupported tarball from /dev/shm/drlkf/with-repo-archive2139961/foo.tar: Symbolic link dest not found from hspec-meta/vendor to hspec-core/vendor/, looking for hspec-meta/hspec-core/vendor.
This may indicate that the source is a git archive which uses git-annex.
See https://github.com/commercialhaskell/stack/issues/4579 for further information.
```
See also: https://github.com/commercialhaskell/stack/issues/5004

Do not symlink to symlinks

---

CHANGES.markdown
changes/qc-chatty.md
doc/_site/options.html
hspec-api/hspec-api.cabal
hspec-core/hspec-core.cabal
hspec-core/src/Test/Hspec/Core/Example.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs
hspec-discover/hspec-discover.cabal
hspec-meta/hspec-meta.cabal
hspec.cabal
version.yaml

Suppresses informational QuickCheck output when `chatty` is `False`

---

hspec-core/hspec-core.cabal
hspec-core/package.yaml
hspec-core/src/GetOpt/Declarative/Types.hs
hspec-core/src/Test/Hspec/Core/Extension.hs
hspec-core/src/Test/Hspec/Core/Extension/Config.hs
hspec-core/src/Test/Hspec/Core/Extension/Config/Type.hs
hspec-core/src/Test/Hspec/Core/Extension/Item.hs
hspec-core/src/Test/Hspec/Core/Extension/Option.hs
hspec-core/src/Test/Hspec/Core/Extension/Spec.hs
hspec-core/src/Test/Hspec/Core/Extension/Tree.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs
hspec-meta/hspec-meta.cabal

This PR adds an extension API that can be used to extend Hspec with additional functionality without the need to modify `hspec-core`.
An example extension that addresses https://github.com/hspec/hspec/issues/338:
```haskell
module Test.Hspec.CI (use, only) where
import System.Environment
import Test.Hspec.Core.Extension
import Test.Hspec.Core.Extension.Item qualified as Item
import Test.Hspec.Core.Extension.Spec qualified as Spec
import Test.Hspec.Core.Extension.Tree qualified as Tree
import Test.Hspec.Core.Extension.Config qualified as Config
-- |
-- Do not run the spec items of the given subtree by default; execute them only
-- when the environment variable @CI@ is set.
--
-- It is idiomatic to use this in combination with `>>>`:
--
-- @
-- import Control.Arrow ((>>>))
-- import …
```

Add extensions API

---

api/Test.Hspec.Runner
hspec-api/api/Test.Hspec.Api.Format.V1
hspec-api/api/Test.Hspec.Api.Format.V2
hspec-api/api/Test.Hspec.Api.Formatters.V2
hspec-api/api/Test.Hspec.Api.Formatters.V3
hspec-core/api/Test.Hspec.Core.Extension
hspec-core/api/Test.Hspec.Core.Extension.Config
hspec-core/api/Test.Hspec.Core.Extension.Item
hspec-core/api/Test.Hspec.Core.Extension.Spec
hspec-core/api/Test.Hspec.Core.Extension.Tree
hspec-core/api/Test.Hspec.Core.Spec
hspec-core/hspec-core.cabal
hspec-core/package.yaml
hspec-core/src/Test/Hspec/Core/Annotations.hs
hspec-core/src/Test/Hspec/Core/Config/Definition.hs
hspec-core/src/Test/Hspec/Core/Config/Options.hs
hspec-core/src/Test/Hspec/Core/Extension.hs
hspec-core/src/Test/Hspec/Core/Extension/Config.hs
hspec-core/src/Test/Hspec/Core/Extension/Config/Type.hs
hspec-core/src/Test/Hspec/Core/Extension/Item.hs
hspec-core/src/Test/Hspec/Core/Extension/Option.hs
hspec-core/src/Test/Hspec/Core/Extension/Spec.hs
hspec-core/src/Test/Hspec/Core/Extension/Tree.hs
hspec-core/src/Test/Hspec/Core/Runner.hs
hspec-core/src/Test/Hspec/Core/Tree.hs
hspec-core/test/Test/Hspec/Core/AnnotationsSpec.hs
hspec-core/test/Test/Hspec/Core/RunnerSpec.hs
hspec-meta/hspec-meta.cabal

Make Hspec extensible
