- doc/index.markdown
@sol Added the link
https://github.com/karun012/arion/issues/1
> Adding a link to Arion

- hspec-core/src/Test/Hspec/Core/Hooks.hs
- hspec-core/test/Test/Hspec/Core/HooksSpec.hs
> Report exceptions in beforeAll operations only once

- doc/quickcheck.md
It took me quite a bit of digging to find out it was possible but I was glad to find out that it's possible to modify the default configuration 🙂
> Add docs on how to configure the quickcheck driver

- doc/options.md
"depends on how your run your tests" should be "depends on how you run your tests"
> Fix you -> your typo in doc/options.md

- CHANGES.markdown
- hspec-contrib/test/Test/Hspec/Contrib/HUnitSpec.hs
- hspec-contrib/test/Test/Hspec/Contrib/RetrySpec.hs
- hspec-core/src/Test/Hspec/Core/Runner.hs
- hspec-core/src/Test/Hspec/Core/Spec.hs
- hspec-core/src/Test/Hspec/Core/Spec/Monad.hs
- hspec-core/src/Test/Hspec/Core/Tree.hs
- hspec-core/test/Test/Hspec/Core/SpecSpec.hs
- src/Test/Hspec.hs
> Allow to focus individual spec items

- hspec-core/hspec-core.cabal
- hspec-core/package.yaml
toNanoSecs was introduced in 0.7.1
> Fix 'clock' lower bound

- src/Test/Hspec.hs
> re-export aroundAll and aroundAllWith

- CHANGES.markdown
- hspec-core/src/Test/Hspec/Core/Format.hs
- hspec-core/src/Test/Hspec/Core/Formatters.hs
- hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs
- hspec-core/src/Test/Hspec/Core/Formatters/Monad.hs
- hspec-core/src/Test/Hspec/Core/Runner/Eval.hs
- hspec-core/test/Test/Hspec/Core/HooksSpec.hs
/cc @hdgarrood (this could be relevant for https://github.com/purescript/purescript/pull/4057)
> Add exampleStarted to Formatter API

- CHANGES.markdown
- hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs
- hspec-core/src/Test/Hspec/Core/Runner.hs
> Rename `getFinalCount` to `getItemCount`

- doc/index.md
Links to issues in Freckle repos:
- https://github.com/freckle/hspec-junit-formatter/issues/7
- https://github.com/freckle/hspec-expectations-json/issues/8
> Add extensions that are maintained by Freckle to listing

- hspec-core/hspec-core.cabal
- hspec-core/src/GetOpt/Declarative.hs
- hspec-core/src/GetOpt/Declarative/Environment.hs
- hspec-core/src/Test/Hspec/Core/Config.hs
- hspec-core/src/Test/Hspec/Core/Config/Options.hs
- hspec-core/test/GetOpt/Declarative/EnvironmentSpec.hs
- hspec-core/test/Test/Hspec/Core/Config/OptionsSpec.hs
- hspec-core/test/Test/Hspec/Core/ConfigSpec.hs
(e.g. `HSPEC_COLOR=yes` will set `--color`)
> Allow to set options by individual environment variables

- CHANGES.markdown
- hspec-core/src/Test/Hspec/Core/Runner.hs
- hspec-core/test/Test/Hspec/Core/RunnerSpec.hs
Blocked by https://github.com/hspec/hspec/issues/512
> Use "checks" formatter by default

- hspec-contrib/test/Test/Hspec/Contrib/HUnitSpec.hs
- hspec-core/src/Test/Hspec/Core/Runner.hs
- hspec-core/src/Test/Hspec/Core/Spec/Monad.hs
- hspec-core/test/Test/Hspec/Core/HooksSpec.hs
- hspec-core/test/Test/Hspec/Core/SpecSpec.hs
This reverts commit a4ecac2a0fec73a44d8886c86000a2684d183b97.
> Revert "Allow to transform the config in SpecM"

- hspec-core/src/Test/Hspec/Core/Hooks.hs
- hspec-core/src/Test/Hspec/Core/Runner.hs
- hspec-core/src/Test/Hspec/Core/Spec/Monad.hs
- hspec-core/src/Test/Hspec/Core/Tree.hs
- hspec-core/test/Test/Hspec/Core/HooksSpec.hs
> Change the type of the `Tree` cleanup action from `a -> IO ()` to `IO ()`

- hspec-core/src/Test/Hspec/Core/Hooks.hs
- hspec-core/test/Test/Hspec/Core/HooksSpec.hs
> Simplify "Call release only when acquired in hooks"

- doc/parallel-spec-execution.md
> Document how to run tests in parallel with hspec-discover

- hspec-core/test/Test/Hspec/Core/Config/OptionsSpec.hs
> test: Ensure that `HSPEC_FAIL_ON` takes precedence over `HSPEC_STRICT`

- hspec-core/hspec-core.cabal
- hspec-core/test/All.hs
- hspec-core/test/Spec.hs
- hspec-core/test/SpecHook.hs
Use `test/SpecHook.hs` intead.
> Don't use `--module-name` for spec discovery

- changes/650.md
- hspec-core/help.txt
- hspec-core/src/Test/Hspec/Core/Config/Definition.hs
- hspec-core/test/Test/Hspec/Core/Config/OptionsSpec.hs
https://github.com/hspec/hspec/issues/650#issuecomment-1243177877
> Do not imply `--fail-on=empty` on `--strict`

- hspec-core/api/Test.Hspec.Core.Runner
- hspec-core/src/Test/Hspec/Core/Runner.hs
- hspec-core/src/Test/Hspec/Core/Runner/Result.hs
- hspec-core/test/Test/Hspec/Core/Runner/ResultSpec.hs
(from `Test.Hspec.Core.Runner`)
> Move `Summary` to `Test.Hspec.Core.Runner.Result`

- CHANGES.markdown
- changes/re-export-sequential.md
- changes/rerun-all.md
- hspec-core/hspec-core.cabal
- hspec-core/src/Test/Hspec/Core/Runner.hs
- hspec-core/test/Test/Hspec/Core/RunnerSpec.hs
- hspec-discover/hspec-discover.cabal
- hspec.cabal
- version.yaml
> Rerun `beforeAll` / `afterAll` on `--rerun-all-on-success`

- hspec-core/src/Test/Hspec/Core/Compat.hs
Caught by https://gitlab.horizon-haskell.net/package-sets/horizon-core/-/jobs/200859
> compatibility with ghc-9.7

- cabal.project
- doc/Makefile
- doc/_data/contents.yml
- doc/_includes/formatter/Monadic.hs
- doc/_includes/formatter/Simple.hs
- doc/_includes/formatter/discover/formatter-example.cabal
- doc/_includes/formatter/discover/package.yaml
- doc/_includes/formatter/discover/src/MyFormatter.hs
- doc/_includes/formatter/discover/test/Data/ListSpec.hs
- doc/_includes/formatter/discover/test/Spec.hs
- doc/_includes/formatter/discover/test/SpecHook.hs
- doc/_plugins/custom.rb
- doc/_site/expectations.html
- doc/_site/extending-hspec-formatter.html
- doc/_site/hspec-discover.html
- doc/_site/hunit.html
- doc/_site/index.html
- doc/_site/match.html
- doc/_site/options.html
- doc/_site/parallel-spec-execution.html
- doc/_site/quickcheck.html
- doc/_site/rerun.html
- doc/_site/running-specs.html
- doc/_site/writing-specs.html
- doc/extending-hspec-formatter.md
> Add documentation on how to extend Hspec with a custom formatter

- CHANGES.markdown
- hspec-api/hspec-api.cabal
- hspec-core/hspec-core.cabal
- hspec-core/package.yaml
- hspec-core/src/Test/Hspec/Core/QuickCheck/Util.hs
- hspec-core/test/Test/Hspec/Core/QuickCheck/UtilSpec.hs
- hspec-core/test/Test/Hspec/Core/RunnerSpec.hs
- hspec-discover/hspec-discover.cabal
- hspec-meta/hspec-meta.cabal
- hspec.cabal
- version.yaml
> Make the build pass with QuickCheck 2.15
